### ISSUE TITLE
FYI language-r development happening at REditorSupport/atom-language-r

### ISSUE THREAD

**Issue by kylebarron** [saeidamiri1/rbox#1]
See this thread: https://github.com/lee-dohm/language-r/issues/25
The REditorSupport organization may become the place for the main development of R language support for Sublime, VSCode, and Atom. The maintainers of Rbox for Sublime and the R language package in VSCode are members of the organization.

**Comment by saeidamiri1** [comment]
Add this Atom package to the REditorSupport organization, I will support it.

**Comment by sdrakulich** [comment]
This seems to be growing into another issue. There are conflicts between rbox and atom-language-r, where I would argue the former does things better as far as implementing the grammar and making better syntax highlighting (commas!!!), but atom-language-r is simply the supported language for various things, including the atom-ide-r package. Is there any intent behind this project to ameliorate this?
