### ISSUE TITLE
Can't see the plot in atom.

### ISSUE THREAD

**Issue by kasanitej** [saeidamiri1/rbox#12]
```
library(party)
iris_decisionTree <- ctree(Species ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width, data=iris)
plot(iris_decisionTree, type = "simple")
```
Above is the code, when I run in the RGui I can able to see the plot, but in the atom, it won't show the plot. Am I doing anything wrong? 

Thanks,
Bhanu.

**Comment by saeidamiri1** [comment]
I run your code,  see the below

<img width="1298" alt="screen shot 2018-12-18 at 3 01 12 pm" src="https://user-images.githubusercontent.com/19543946/50179812-01ebd380-02d6-11e9-8ff8-ae3dfb46646f.png">

A short explanations how to run codes using Atom is https://github.com/saeidamiri1/rbox/wiki. If you want to run inline, install IRkernel and hydrogen.
