### ISSUE TITLE
"illegal" syntax

### ISSUE THREAD

**Issue by sgsokol** [saeidamiri1/rbox#2]
Sometimes, I have part of my code colored in flashy red like it was written with erroneous syntax. For example, in a code `i=1L` the text `1L` will be signaled with this alarm-red color. However, it is a perfectly legal syntax in R indicating a long integer.
Another example, `x >= 0`, here it is `>=` which is signaled. And once again it is perfectly correct construct, well understood by R.
May be I am wrong in interpretation of the red color?

**Comment by saeidamiri1** [comment]
Thanks, you are right, I will correct them in the next version.

**Comment by saeidamiri1** [comment]
It is corrected  now.

**Comment by sgsokol** [comment]
Thanks for the patch.
One more thing. The patch is working well for one-digit numbers like '1L' but two- or more-digits numbers (like '12L') they are still in red.
