### ISSUE TITLE
any feature can support a R Console？

### ISSUE THREAD

**Issue by ShixiangWang** [saeidamiri1/rbox#6]
This package is a great work , thanks very much.  I did not see a package can provide a R console，can you add this feature?

**Comment by saeidamiri1** [comment]
I am happy, you like it, it is still immature, the better version is onway.  First Install IRkernel, Hydrogen and Termination in your ATOM. 

Using Hydrogen you can run the code inline like Jupyter that is amazing property. Note, to run your codes using Hydrogen, first save your file, Hydrogen automatically recognizes IRkernel. 
You can find a short description:  https://github.com/saeidamiri1/rbox/wiki/Use-under-macOS 

Using Termination; you can run R console via Terminal, you can run several R consoles simultaneously. See You can find a short description:  https://github.com/saeidamiri1/rbox/wiki/Use-under-macOS.
